<?php

declare(strict_types=1);

namespace App\Domains\Integrations\Providers\Snapchat;

/**
 * SNAP-OCT26 — the words Snapchat's Marketing API uses in 2026, named once.
 *
 * Placements (`placement_v2.snapchat_positions`): the documented positions, with the Chat Feed
 * placement Snapchat opened to lower-funnel bundling in May 2026. A token this list does not know is
 * kept VERBATIM and never hidden — a placement the product has not named is still where the money
 * went. Nothing here is invented: «In-stream Spotlight» is not a position token in the documentation
 * the lane could read, so it is not declared here and its ledger row says so.
 *
 * AI media (`ai_content_source` on a media object): the declaration an advertiser makes that a file
 * is AI-generated or AI-modified (`USER_AI_GEN`), or that Snap made (`SNAP_AI_GENERATED`). Read on
 * every creative whose media carries it; required on any media this product ever writes.
 *
 * Errors: `E9001` is the one code Snapchat documents for a synchronous stats request whose answer
 * would be too large — the fix is fewer fields, a shorter window, or asynchronous reporting. It is
 * mapped to that sentence and a retry rule, never shown as a bare code.
 */
final class SnapchatVocabulary
{
    /** @var array<string, array{ar: string, en: string}> */
    public const PLACEMENTS = [
        'FEED' => ['ar' => 'الخلاصة', 'en' => 'Feed'],
        'CHAT_FEED' => ['ar' => 'خلاصة الدردشة', 'en' => 'Chat Feed'],
        'INTERSTITIAL_USER' => ['ar' => 'بين قصص المستخدمين', 'en' => 'Between user stories'],
        'INTERSTITIAL_CONTENT' => ['ar' => 'بين محتوى الناشرين', 'en' => 'Between publisher content'],
        'SPOTLIGHT' => ['ar' => 'سبوتلايت', 'en' => 'Spotlight'],
        'CAMERA' => ['ar' => 'الكاميرا', 'en' => 'Camera'],
    ];

    /** @var array<string, array{ar: string, en: string}> */
    public const AI_MEDIA = [
        'USER_AI_GEN' => ['ar' => 'أعلن المعلن أنها مولَّدة أو معدَّلة بالذكاء الاصطناعي', 'en' => 'Declared by the advertiser as AI-generated or AI-modified'],
        'SNAP_AI_GENERATED' => ['ar' => 'ولَّدتها سناب بالذكاء الاصطناعي', 'en' => 'Generated by Snap with AI'],
    ];

    public const E9001 = 'E9001';

    /**
     * The placements an ad squad runs in, read from `placement_v2`. Null when the squad carries none.
     *
     * @param  array<string, mixed>  $squad
     * @return array{placement_config: ?string, placements: list<string>}|null
     */
    public static function placements(array $squad): ?array
    {
        $v2 = $squad['placement_v2'] ?? null;
        if (! is_array($v2)) {
            return null;
        }
        $positions = [];
        foreach ((array) ($v2['snapchat_positions'] ?? []) as $position) {
            if (is_string($position) && $position !== '') {
                $positions[] = strtoupper($position);
            }
        }
        $config = isset($v2['config']) && is_string($v2['config']) ? strtolower($v2['config']) : null;

        if ($positions === [] && $config === null) {
            return null;
        }

        return ['placement_config' => $config, 'placements' => array_values(array_unique($positions))];
    }

    /** The placement's name in the reader's language, or the token itself when the product has not named it. */
    public static function placementLabel(string $token, string $locale): string
    {
        $t = strtoupper($token);

        return self::PLACEMENTS[$t][$locale === 'ar' ? 'ar' : 'en'] ?? $token;
    }

    /**
     * The AI declaration a media object carries, normalised; null when it carries none.
     *
     * @param  array<string, mixed>|null  $media
     */
    public static function aiContentSource(?array $media): ?string
    {
        $value = $media['ai_content_source'] ?? null;

        return is_string($value) && trim($value) !== '' ? strtoupper(trim($value)) : null;
    }

    /**
     * What an error code means to the operator, and what to do — or null for a code this list does not know.
     *
     * @return array{code: string, message_ar: string, message_en: string, retry: string}|null
     */
    public static function explainError(?string $code): ?array
    {
        if ($code === null) {
            return null;
        }

        return match (strtoupper(trim($code))) {
            self::E9001 => [
                'code' => self::E9001,
                'message_ar' => 'رفضت سناب شات طلب الإحصاءات لأن الاستجابة أكبر من حدّها (E9001): يُعاد الطلب بحقول أقل أو فترة أقصر، أو عبر التقارير غير المتزامنة.',
                'message_en' => 'Snapchat refused the stats request because the answer would be larger than its limit (E9001): ask again with fewer fields or a shorter window, or through asynchronous reporting.',
                'retry' => 'split_window',
            ],
            default => null,
        };
    }

    /**
     * SNAP-OCT26-SUBREQUEST-WARNINGS — one element of a paged read that did not succeed on its own.
     *
     * Snapchat answers a list request with one `sub_request_status` per element; an element can fail
     * while the request as a whole says SUCCESS. Until now the element was simply absent from the
     * result. This names it, with the reason Snapchat gave, verbatim.
     *
     * @param  array<string, mixed>  $wrapper
     * @return array{what: string, id: ?string, status: string, reason: ?string}|null
     */
    public static function subRequestWarning(array $wrapper, string $key, string $what): ?array
    {
        $status = $wrapper['sub_request_status'] ?? null;
        if (! is_string($status) || strtoupper($status) === 'SUCCESS') {
            return null;
        }
        $entity = (array) ($wrapper[$key] ?? []);
        $reason = null;
        foreach (['sub_request_error_reason', 'debug_message', 'display_message'] as $k) {
            if (isset($wrapper[$k]) && is_string($wrapper[$k]) && $wrapper[$k] !== '') {
                $reason = $wrapper[$k];
                break;
            }
        }

        return [
            'what' => $what,
            'id' => isset($entity['id']) ? (string) $entity['id'] : null,
            'status' => strtoupper($status),
            'reason' => $reason,
        ];
    }
}
