<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Domains\Access\Models\Permission;
use App\Domains\Access\Models\Role;
use App\Domains\Integrations\Catalogue\ProviderCatalogue;
use App\Domains\Integrations\Models\ProviderConnection;
use App\Domains\Integrations\OAuth\OAuthTokens;
use App\Domains\Integrations\OAuth\PlatformCredentials;
use App\Domains\Integrations\OAuth\PlatformOAuth;
use App\Domains\Tenancy\Context\TenantContext;
use App\Domains\Tenancy\Models\Tenant;
use App\Models\User;
use Database\Seeders\PermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

/**
 * TIKTOK-AUTH-001 — TikTok sends back TWO codes, and we were exchanging the wrong one.
 *
 * ## The defect
 *
 * `AdPlatformOAuthController::callback` reads `$request->query('code')` for every provider, and
 * `PlatformOAuth::exchangeCode()` posts that value to TikTok as `auth_code`. For the five providers
 * that follow RFC 6749 that is correct. TikTok does not follow it here.
 *
 * The current Marketing API authorization documentation shows the redirect it actually performs:
 *
 * ```
 * …?state=your_custom_params
 *   &code=3c6dc21d2db289199737bcb8c006c23aaf000a1e
 *   &auth_code=1234c21d2db289199737bcb8c006c23aaf000a1e
 *   &id=1701890905779201
 * ```
 *
 * **Two different values.** And the page then says, of that exact example, that the code to extract is
 * `1234c21d…` — the value in `auth_code`, not the one in `code`. The authentication page agrees:
 * `auth_code` is «the authorization code generated by your Advertiser authorization URL», it is valid
 * for one hour and may be used once.
 *
 * So the connect flow took TikTok's `code`, posted it as `auth_code`, and TikTok refused it. Not
 * intermittently and not for some advertisers — **every TikTok connection attempt, always.** It was
 * invisible here because no test drove the callback with the pair of parameters a real TikTok redirect
 * carries: a fixture that sends only `code` cannot tell the two apart, and that is the fixture the
 * flow test used.
 *
 * ## The second correction: the documented request body has three fields
 *
 * The published request is exactly `{app_id, secret, auth_code}`, all three required, and there is no
 * `grant_type` anywhere in it — that parameter was carried over from the OAuth vocabulary TikTok is
 * not speaking. It is removed rather than left in on the theory that an unknown field is probably
 * ignored, because «probably ignored» is not something to find out on a customer's first connection.
 *
 * ## What this audit CONFIRMED rather than changed
 *
 * Read from the same two pages, so the next reader does not have to re-derive it:
 *
 *  - **The token does not expire.** «A long-term access token does not expire, but it'll become
 *    invalid if the advertiser cancels the authorization.» The catalogue already said this and
 *    `supportsRefresh: false` is right — TikTok publishes no refresh grant, and a caller treating
 *    "cannot refresh" as an error would mark a healthy connection broken.
 *  - **Scopes belong to the app, not to the authorise URL.** The advertiser approves the permissions
 *    chosen when the app was created, so sending `scope` would be meaningless — and the granted scope
 *    comes BACK on the token response.
 *  - **`/oauth2/advertiser/get/` is the documented way** to list every advertiser a token can reach,
 *    which is what the connector already uses. Discovery is per customer, from the customer's own
 *    token, and no advertiser id is a system credential.
 *  - **No PKCE.** TikTok's flow has no code challenge or verifier.
 */
final class TikTokAuthorizationCodeTest extends TestCase
{
    use RefreshDatabase;

    /** The two values TikTok's own documented redirect carries — deliberately different, as there. */
    private const RETURNED_CODE = '3c6dc21d2db289199737bcb8c006c23aaf000a1e';

    private const RETURNED_AUTH_CODE = '1234c21d2db289199737bcb8c006c23aaf000a1e';

    private Tenant $tenant;

    private User $owner;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seed(PermissionSeeder::class);

        $this->tenant = Tenant::create(['name' => 'T', 'slug' => 't-'.uniqid(), 'status' => 'active']);
        app(TenantContext::class)->setTenantId($this->tenant->id);

        $role = Role::create(['tenant_id' => $this->tenant->id, 'name' => 'Owner', 'slug' => 'owner']);
        $role->givePermissionTo(...Permission::pluck('key')->all());

        $this->owner = User::create(['name' => 'O', 'email' => 'o@t.test', 'password' => 'secret123']);
        $this->grantMembership($this->owner, $this->tenant);
        $this->owner->assignRole($role);

        foreach (PlatformCredentials::for('tiktok')->requires() as $key) {
            config()->set("ad_platforms.platforms.tiktok.{$key}", "test-{$key}");
        }
    }

    /**
     * **The defect, pinned.** A real TikTok redirect carries both; only `auth_code` is exchangeable.
     *
     * Under the old code the outgoing body carried `3c6dc21d…` and TikTok refused it.
     */
    public function test_the_callback_exchanges_the_auth_code_parameter_and_not_the_code_parameter(): void
    {
        $this->fakeTikTok();

        $state = $this->startAndTakeState();

        $this->get('/api/v1/oauth/ads/tiktok/callback?'.http_build_query([
            'code' => self::RETURNED_CODE,
            'auth_code' => self::RETURNED_AUTH_CODE,
            'id' => '1701890905779201',
            'state' => $state,
        ]))->assertRedirectContains('outcome=connected');

        Http::assertSent(function ($request) {
            if (! str_contains($request->url(), 'oauth2/access_token')) {
                return true;
            }

            $this->assertSame(self::RETURNED_AUTH_CODE, $request['auth_code']);
            $this->assertNotSame(self::RETURNED_CODE, $request['auth_code']);

            return true;
        });
    }

    /**
     * The documented request body is exactly three fields. No `grant_type`, no `code`, no redirect uri.
     */
    public function test_the_token_request_carries_exactly_the_three_documented_parameters(): void
    {
        $this->fakeTikTok();

        $this->get('/api/v1/oauth/ads/tiktok/callback?'.http_build_query([
            'code' => self::RETURNED_CODE,
            'auth_code' => self::RETURNED_AUTH_CODE,
            'state' => $this->startAndTakeState(),
        ]))->assertRedirectContains('outcome=connected');

        Http::assertSent(function ($request) {
            if (! str_contains($request->url(), 'oauth2/access_token')) {
                return true;
            }

            $this->assertSame(
                ['app_id', 'auth_code', 'secret'],
                collect(array_keys((array) $request->data()))->sort()->values()->all(),
            );

            return true;
        });
    }

    /**
     * A TikTok callback carrying only `code` exchanges NOTHING.
     *
     * The tempting fix is «read auth_code, fall back to code». That fallback would post the value we
     * now know is wrong, receive a refusal, and report it to the customer as a platform failure — the
     * exact behaviour being removed, kept alive as a safety net. If the parameter TikTok documents is
     * absent, the honest answer is that the redirect was not the one TikTok describes.
     */
    public function test_a_tiktok_callback_without_an_auth_code_exchanges_nothing(): void
    {
        Http::preventStrayRequests();
        Http::fake();

        $this->get('/api/v1/oauth/ads/tiktok/callback?'.http_build_query([
            'code' => self::RETURNED_CODE,
            'state' => $this->startAndTakeState(),
        ]))->assertRedirectContains('outcome=failed');

        $this->assertSame(0, ProviderConnection::withoutGlobalScopes()->count());
        Http::assertNothingSent();
    }

    /**
     * The five providers that DO speak OAuth keep reading `code`.
     *
     * This is the regression guard on the shape of the fix: the knowledge that TikTok differs belongs
     * in the one place the other four TikTok bends already live, and must not leak into everybody else.
     */
    public function test_the_other_providers_still_read_the_standard_code_parameter(): void
    {
        foreach (PlatformCredentials::for('meta')->requires() as $key) {
            config()->set("ad_platforms.platforms.meta.{$key}", "test-{$key}");
        }

        Http::fake([
            'graph.facebook.com/*/oauth/access_token*' => Http::response(['access_token' => 'AT', 'expires_in' => 5184000]),
            'graph.facebook.com/*/me/adaccounts*' => Http::response(['data' => []]),
        ]);

        $url = $this->actingAs($this->owner, 'sanctum')
            ->postJson('/api/v1/integrations/meta/oauth/start')->assertOk()->json('data.authorization_url');
        parse_str((string) parse_url((string) $url, PHP_URL_QUERY), $query);

        $this->get("/api/v1/oauth/ads/meta/callback?code=meta-code&state={$query['state']}")
            ->assertRedirectContains('outcome=connected');

        Http::assertSent(function ($request) {
            if (! str_contains($request->url(), 'oauth/access_token')) {
                return true;
            }

            $this->assertSame('meta-code', $request['code']);

            return true;
        });
    }

    /**
     * A long-term token is stored with NO expiry, and asking to refresh it returns it unchanged.
     *
     * TikTok sends no `expires_in`, so an expiry must not be invented; and there is no refresh grant
     * to call, so `refresh()` hands back what it was given rather than throwing. A connection whose
     * token is valid until the advertiser revokes it should never be marked as needing reconnection.
     */
    public function test_a_long_term_token_has_no_expiry_and_refreshing_it_is_a_no_op(): void
    {
        $creds = PlatformCredentials::for('tiktok');

        Http::fake(['business-api.tiktok.com/open_api/*/oauth2/access_token*' => Http::response([
            'code' => 0,
            'data' => ['access_token' => 'long-term', 'advertiser_ids' => ['123'], 'scope' => [4]],
        ])]);

        $tokens = app(PlatformOAuth::class)->exchangeCode($creds, self::RETURNED_AUTH_CODE);

        $this->assertSame('long-term', $tokens->accessToken);
        $this->assertNull($tokens->expiresAt, 'TikTok publishes no expires_in; inventing one would force needless reconnections');
        $this->assertNull($tokens->refreshToken);

        // The advertiser list and granted scope TikTok returns with the token are kept, not discarded.
        $this->assertSame(['123'], $tokens->raw['advertiser_ids']);

        $refreshed = app(PlatformOAuth::class)->refresh($creds, new OAuthTokens('long-term', null, null));
        $this->assertSame('long-term', $refreshed->accessToken);
    }

    /**
     * The catalogue's stated token lifetime is the documented one, in both languages.
     *
     * Verified against «A long-term access token does not expire, but it'll become invalid if the
     * advertiser cancels the authorization.» — so the interface must not promise a refresh, and must
     * tell an operator that a dead TikTok connection means re-authorisation, not a token rotation.
     */
    public function test_the_stated_token_lifecycle_matches_the_documentation(): void
    {
        $definition = ProviderCatalogue::get('tiktok');

        $this->assertFalse($definition->supportsRefresh);
        $this->assertFalse($definition->usesPkce, 'TikTok publishes no code challenge or verifier');
        $this->assertStringContainsString('does not expire', strtolower((string) $definition->tokenNote));
        $this->assertStringNotContainsString('refresh token', strtolower((string) $definition->tokenNoteAr));
    }

    /**
     * No advertiser id is a system credential — the same rule SNAP-ORG-001 established for Snapchat.
     *
     * The token response itself names the advertisers it can reach, and `/oauth2/advertiser/get/`
     * lists them in full. Neither is anything a platform operator could type in at `/admin`, and a
     * single one stored there could not be right for a second customer.
     */
    public function test_the_platform_form_asks_for_the_app_and_nothing_belonging_to_a_customer(): void
    {
        $keys = array_map(static fn ($f) => $f->key, ProviderCatalogue::get('tiktok')->fields);

        $this->assertSame(['client_id', 'client_secret'], $keys);
        $this->assertNotContains('advertiser_id', $keys);
        $this->assertNotContains('business_center_id', $keys);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────────────────────

    private function fakeTikTok(): void
    {
        Http::fake([
            'business-api.tiktok.com/open_api/*/oauth2/access_token*' => Http::response([
                'code' => 0,
                'data' => ['access_token' => 'AT', 'advertiser_ids' => ['777'], 'scope' => [4]],
            ]),
            'business-api.tiktok.com/open_api/*/oauth2/advertiser/get*' => Http::response([
                'code' => 0,
                'data' => ['list' => [
                    ['advertiser_id' => '777', 'advertiser_name' => 'Advertiser', 'currency' => 'SAR'],
                ]],
            ]),
        ]);
    }

    private function startAndTakeState(): string
    {
        $url = $this->actingAs($this->owner, 'sanctum')
            ->postJson('/api/v1/integrations/tiktok/oauth/start')
            ->assertOk()
            ->json('data.authorization_url');

        parse_str((string) parse_url((string) $url, PHP_URL_QUERY), $query);

        return (string) $query['state'];
    }
}
